name: Build Flutter APK

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Build Admin APK
        working-directory: frontend
        run: |
          flutter build apk --release --flavor admin --dart-define=IS_ADMIN=true

      - name: Build User APK
        working-directory: frontend
        run: |
          flutter build apk --release --flavor user --dart-define=IS_ADMIN=false

      - name: Upload APKs to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_number }}"
          name: "Build #${{ github.run_number }}"
          files: |
            frontend/build/app/outputs/flutter-apk/app-admin-release.apk
            frontend/build/app/outputs/flutter-apk/app-user-release.apk
